nayotta/metathings

Makefile, dockerfile/Dockerfile.protobuf-maker, script/docker_build_development.sh
=> :rocket: add protobuf maker Docker for MT

pkg/identityd2/service/create_entity.go
=> :bug: hotfix unhashed password

pkg/identityd2/storage/storage_impl.go
=> :bug: failed to delete entity

pkg/identityd2/service/create_action.go, pkg/identityd2/service/create_domain.go, pkg/identityd2/service/create_role.go
=> :bug: fix identityd2 create action error

pkg/identityd2/service/add_role_to_group.go, pkg/identityd2/storage/storage.go, pkg/identityd2/storage/storage_impl.go
=> :bug: failed to cretae group

pkg/identityd2/storage/storage_impl.go
=> :bug: fix issue48_authorize_token_error

pkg/component/kernel.go, pkg/identityd2/policy/casbin_backend.go, pkg/policyd/casbin-server/server/enforcer.go
=> :bug: enforce too slow when too many casbin rules

pkg/identityd2/service/add_action_to_role.go, pkg/identityd2/service/add_entity_to_domain.go, pkg/identityd2/service/add_object_to_group.go, pkg/identityd2/service/add_role_to_entity.go, pkg/identityd2/service/add_role_to_group.go, pkg/identityd2/service/add_subject_to_group.go, pkg/identityd2/service/create_action.go, pkg/identityd2/service/create_domain.go, pkg/identityd2/service/delete_credential.go, pkg/identityd2/service/delete_group.go, pkg/identityd2/service/get_credential.go, pkg/identityd2/service/get_domain.go, pkg/identityd2/service/get_entity.go, pkg/identityd2/service/get_group.go, pkg/identityd2/service/get_role.go, pkg/identityd2/service/helper.go, pkg/identityd2/service/remove_action_from_role.go, pkg/identityd2/service/remove_entity_from_domain.go, pkg/identityd2/service/remove_object_from_group.go, pkg/identityd2/service/remove_role_from_entity.go, pkg/identityd2/service/remove_role_from_group.go, pkg/identityd2/service/remove_subject_from_group.go, pkg/identityd2/service/revoke_token.go, pkg/identityd2/service/service.go
关联 #60 
部分创建资源和列表接口还未添加认证和授权功能.
=> :tada: validate and authorize for interfaces

pkg/identityd2/service/add_action_to_role.go, pkg/identityd2/service/add_entity_to_domain.go, pkg/identityd2/service/add_object_to_group.go, pkg/identityd2/service/add_role_to_entity.go, pkg/identityd2/service/add_role_to_group.go, pkg/identityd2/service/add_subject_to_group.go, pkg/identityd2/service/create_action.go, pkg/identityd2/service/create_domain.go, pkg/identityd2/service/delete_credential.go, pkg/identityd2/service/delete_group.go, pkg/identityd2/service/get_credential.go, pkg/identityd2/service/get_domain.go, pkg/identityd2/service/get_entity.go, pkg/identityd2/service/get_group.go, pkg/identityd2/service/get_role.go, pkg/identityd2/service/helper.go, pkg/identityd2/service/issue_token_by_credential.go, pkg/identityd2/service/remove_action_from_role.go, pkg/identityd2/service/remove_entity_from_domain.go, pkg/identityd2/service/remove_object_from_group.go, pkg/identityd2/service/remove_role_from_entity.go, pkg/identityd2/service/remove_role_from_group.go, pkg/identityd2/service/remove_subject_from_group.go, pkg/identityd2/service/revoke_token.go, pkg/identityd2/service/service.go
=> Issue62 credential expiresat not work

cmd/metathingsd/cmd/identityd2.go, pkg/identityd2/service/add_action_to_role.go, pkg/identityd2/service/add_entity_to_domain.go, pkg/identityd2/service/add_object_to_group.go, pkg/identityd2/service/add_role_to_entity.go, pkg/identityd2/service/add_role_to_group.go, pkg/identityd2/service/add_subject_to_group.go, pkg/identityd2/service/create_action.go, pkg/identityd2/service/create_credential.go, pkg/identityd2/service/create_domain.go, pkg/identityd2/service/delete_credential.go, pkg/identityd2/service/delete_group.go, pkg/identityd2/service/get_credential.go, pkg/identityd2/service/get_domain.go, pkg/identityd2/service/get_entity.go, pkg/identityd2/service/get_group.go, pkg/identityd2/service/get_role.go, pkg/identityd2/service/helper.go, pkg/identityd2/service/remove_action_from_role.go, pkg/identityd2/service/remove_entity_from_domain.go, pkg/identityd2/service/remove_object_from_group.go, pkg/identityd2/service/remove_role_from_entity.go, pkg/identityd2/service/remove_role_from_group.go, pkg/identityd2/service/remove_subject_from_group.go, pkg/identityd2/service/revoke_token.go, pkg/identityd2/service/service.go
=> Issue63 create credential with too short expires

examples/03-push-frame-to-flow/main.go, examples/04-pull-frame-from-flow/main.go
=> :tada: add flow client

pkg/deviced/connection/connection.go, pkg/deviced/connection/errors.go, pkg/deviced/service/errors.go, pkg/deviced/service/helper.go, pkg/deviced/service/unary_call.go
=> :bug: service crash when device offline

cmd/contrib/client_factory.go, cmd/metathings/cmd/run_device.go, pkg/common/client/helper.go, pkg/component/kernel.go, pkg/device/service/handle.go, pkg/device/service/heartbeat.go, pkg/device/service/helper.go, pkg/device/service/main_loop.go, pkg/device/service/service.go, pkg/device/service/start.go, pkg/deviced/connection/sarama_bridge.go
=> Issue81 deviced memory leak

cmd/contrib/client_factory.go, cmd/metathings/cmd/run_device.go, pkg/common/client/helper.go, pkg/component/kernel.go, pkg/device/service/handle.go, pkg/device/service/heartbeat.go, pkg/device/service/helper.go, pkg/device/service/main_loop.go, pkg/device/service/service.go, pkg/device/service/start.go
=> Issue75 reconnect device

cmd/metathings/cmd/run_device.go, pkg/device/service/handle.go, pkg/device/service/heartbeat.go, pkg/device/service/helper.go, pkg/device/service/main_loop.go, pkg/device/service/service.go, pkg/device/service/start.go, pkg/deviced/connection/connection.go
=> Issue79 crash when restart kafka

pkg/identityd2/service/issue_token_by_password.go
=> :bug: nouser entity should not issue token by password

pkg/identityd2/service/errors.go, pkg/identityd2/service/service.go
=> 修复 identityd2崩溃问题

pkg/deviced/connection/connection.go, pkg/identityd2/service/errors.go, pkg/identityd2/service/service.go
=> 修复 identityd2奔溃问题

cmd/metathings/cmd/run_device.go, pkg/common/fx/helper.go, pkg/common/grpc/helper.go, pkg/device/service/handle.go, pkg/device/service/main_loop.go, pkg/device/service/ping.go, pkg/device/service/service.go, pkg/device/service/start.go, pkg/deviced/connection/connection.go, pkg/deviced/connection/interceptor.go, pkg/deviced/service/connect.go, pkg/deviced/service/service.go
=> 修复 device 离线问题

openapi/device/openapi.yaml
=> :bug: fix openapi format error

cmd/contrib/base.go, cmd/contrib/client_factory.go, cmd/contrib/transport_credentials.go, cmd/metathings/cmd/issue_token.go, cmd/metathings/cmd/root.go, cmd/metathings/cmd/run_device.go, cmd/metathingsd/cmd/device_cloud.go, cmd/metathingsd/cmd/root.go, pkg/common/client/helper.go, pkg/component/kernel.go, pkg/component/module.go, pkg/identityd2/policy/casbin_backend_test.go
=> :tada: tls support

cmd/contrib/transport_credentials.go
=> :bug: support common credentials

cmd/contrib/transport_credentials.go, cmd/metathings/cmd/run_device.go, pkg/component/kernel.go
=> :bug: module failed to online

pkg/tagd/service/helper.go, pkg/tagd/service/remove.go, pkg/tagd/service/untag.go
=> Issue162 tagd error

cmd/contrib/service_endpoint.go, cmd/metathings/cmd/issue_token.go
=> :bug: failed to load command line arguments

pkg/common/file/sync.go, pkg/common/log/log.go, pkg/component/kernel.go, pkg/deviced/service/put_object_streaming.go
=> :bug: dirty memory wirte

pkg/deviced/simple_storage/file_simple_storage.go
=> Issue184 get object with directory

pkg/identityd2/storage/storage_impl.go
=> :bug: ignore tracer when it is nil

cmd/metathingsd/cmd/device_cloud.go, etc/device_cloud.template.yaml, pkg/common/option/helper.go, pkg/device_cloud/service/connection.go, pkg/device_cloud/service/errors.go, pkg/device_cloud/service/flow.go, pkg/device_cloud/service/mqtt_flow_channel.go, pkg/device_cloud/service/service.go, pkg/device_cloud/storage/redis_storage.go, pkg/device_cloud/storage/storage.go
=> 修复 module heartbeat 过短问题

contrib/extra/extra.go, pkg/common/storage/update_extra.go, pkg/deviced/service/create_device.go, pkg/deviced/service/patch_device.go, pkg/deviced/storage/storage.go, pkg/deviced/storage/storage_impl.go, pkg/identityd2/service/check_token.go, pkg/identityd2/service/create_action.go, pkg/identityd2/service/create_domain.go, pkg/identityd2/service/create_entity.go, pkg/identityd2/service/create_group.go, pkg/identityd2/service/create_role.go, pkg/identityd2/service/list_actions.go, pkg/identityd2/service/patch_action.go, pkg/identityd2/service/patch_domain.go, pkg/identityd2/service/patch_entity.go, pkg/identityd2/service/patch_group.go, pkg/identityd2/service/patch_role.go, pkg/identityd2/service/validate_token.go, pkg/identityd2/storage/storage.go, pkg/identityd2/storage/storage_impl.go
=> :tada: add extra protcol

go.mod, pkg/common/client/helper.go, pkg/common/context/helper.go, pkg/common/option/helper.go, pkg/common/protobuf/helper.go, pkg/deviced/service/get_flow_set.go, pkg/deviced/service/list_objects.go, pkg/evaluatord/service/create_evaluator.go, pkg/evaluatord/service/patch_evaluator.go, pkg/plugin/evaluator/cmd/evaluator.go, pkg/plugin/evaluator/evaluator_impl.go, pkg/plugin/evaluator/lua_operator.go, pkg/plugin/evaluator/lua_operator_core.go, pkg/plugin/evaluator/lua_operator_core_device.go, pkg/plugin/evaluator/lua_operator_core_simple_storage.go, pkg/plugin/evaluator/lua_operator_core_storage.go, pkg/plugin/evaluator/lua_operator_test.go, pkg/plugin/evaluator/service/evaluator.go, sdk/data_storage/mock.go, sdk/deviced/deviced_simple_storage.go, sdk/deviced/errors.go, sdk/deviced/mock_simple_storage.go, sdk/deviced/options.go, sdk/deviced/simple_storage.go
=> 215 evaluator with simple storage

openapi/device_cloud/openapi.yaml
=> :bug: openapi typo error

examples/01-unary-call/main.go
=> :tada: rewrite examples01

examples/10-pull-frame-from-flow-set/main.go, pkg/common/rand/helper.go, pkg/deviced/flow/flow_impl.go, pkg/deviced/flow/redis_stream_flow_set.go
=> Issue249 remove outdated flow stream message

pkg/identityd2/service/helper.go
=> :tada: change long time token expire time from 100 years to 7 days

go.mod, go.sum, pkg/device_cloud/service/connection.go
=> :bug: add retry to unset device and module session

pkg/deviced/service/stream_call.go, pkg/deviced/service/unary_call.go
=> :loud_sound: add more logs for unary call and stream call

pkg/plugin/evaluator/evaluator.go, pkg/plugin/evaluator/evaluator_impl.go, pkg/plugin/evaluator/service/eval.go, sdk/evaluatord/data.go
=> :tada: add evaluator result to task tags

cmd/metathings/cmd/run_device.go, examples/08-push-frame-to-flow-mqtt/main.go, go.mod, go.sum, pkg/plugin/evaluator/cmd/evaluator.go, pkg/plugin/evaluator/evaluator_impl.go, pkg/plugin/evaluator/lua_operator.go, pkg/plugin/evaluator/lua_operator_core.go, pkg/plugin/evaluator/lua_operator_core_sms.go, pkg/plugin/evaluator/lua_operator_test.go, pkg/plugin/evaluator/service/eval.go, pkg/plugin/evaluator/service/evaluator.go, sdk/sms/dummy.go, sdk/sms/errors.go, sdk/sms/mock_sms_sender.go, sdk/sms/pomelo_sender.go, sdk/sms/pomelo_sender_test.go, sdk/sms/sender.go
=> Issue232 support pomelo

pkg/evaluatord/storage/storage_impl.go
=> :bug: add where scope to update lua descriptor code

examples/01-unary-call/main.go, sdk/deviced/deviced_simple_storage.go
=> :bug: replace gogo jsonpb to golang jsonpb

pkg/device_cloud/service/handle.go, pkg/device_cloud/service/mqtt_flow_channel.go, pkg/device_cloud/service/sync_firmware.go
=> Issue312 mqtt connection leak
